server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: SYSTEM
    password: admin
    driver-class-name: oracle.jdbc.OracleDriver
# swagger link: http://localhost:8080/api/v1/swagger-ui/index.html
